namespace LibraryManagementAPI.Async.DTOs.BookIssue
{
    public class BookIssueReadDTO
    {
        public int Id { get; set; } // The primary key generated by your database
        public int BookId { get; set; }
        public int StudentId { get; set; }
        public DateTime IssueDate { get; set; }
        public DateTime ReturnDate { get; set; }
        public bool Status { get; set; }
    }
}
